#!/usr/bin/env python

import gtk
import MySQLdb


class conexion1:
	
	def __init__(self):
		
		db_host = 'localhost'
		usuario = 'root'
		clave= 'toor'
		base_de_datos= 'bdUsuarios'
		
		db = MySQLdb.connect(host=db_host, user=usuario, passwd=clave, db=base_de_datos)

		return db
